### ISSUE TITLE
Feature request: Implement B&O protocol

### ISSUE THREAD

**Issue by Ion3** [shirriff/Arduino-IRremote#56] opened 2014-03-19 15:48 UTC
Is it possible to implement the Bang & Olufsen protocol based on this project?

https://github.com/christianlykke9/Beomote

I would love to have the possibility to send B & O signals with my Arduino!

**Comment by z3t0** [comment] 2015-03-07 05:53
@Ion3 The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'. This will be considered as an idea for a future library.

**Closed by z3t0** 2015-03-07 05:53 UTC
