### ISSUE TITLE
Lego power function remote support.

### ISSUE THREAD

**Issue by emuboy** [shirriff/Arduino-IRremote#55] opened 2014-03-19 12:46 UTC
Should be nice to have the Lego power function remote support, the protocoll is well know:

http://www.hackvandedam.nl/blog/?page_id=559

I have the 8885 dual joystick, eventually I can test it if needed.

**Comment by z3t0** [comment] 2015-03-07 05:54
@emuboy I would like to help work on this, please comment if you are still interested.

**Comment by z3t0** [comment] 2015-03-07 05:55
@emuboy The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'.

**Closed by z3t0** 2015-03-07 05:55 UTC
Labels: WIP
