### ISSUE TITLE
Zigduino Compatibility

### ISSUE THREAD

**Issue by artalat** [shirriff/Arduino-IRremote#15] opened 2012-08-26 12:54 UTC
Hey, my code is working fine with Arduino UNO but it's not working with Zigduino (Arduino Compatible board). The board uses ATmega128RFA1 MCU. Any ideas how to make it work?

Zigduino URL: http://logos-electro.wikidot.com/zigduino

**Comment by z3t0** [comment] 2015-03-07 20:27
@artalat The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'.

**Comment by z3t0** [comment] 2015-03-07 20:27
@artalat I will still look into this, but this issue has been closed because the board is not supported by this library.

**Closed by z3t0** 2015-03-07 20:27 UTC
