### ISSUE TITLE
IRremote for node

### ISSUE THREAD

**Issue by GuySawyer** [shirriff/Arduino-IRremote#59] opened 2014-04-24 10:27 UTC
Good day

Looks good what you have done here. Just a question from me.

I am using a beaglebone black and trying to build an IR transceiver. I need to record IR signals and then send them, all from within a Node.js application on the beaglebone. Do you know of anyone that has done something similar?

**Comment by z3t0** [comment] 2015-03-07 05:49
@GuySawyer The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'

**Closed by z3t0** 2015-03-07 05:49 UTC
