### ISSUE TITLE
Conflict with TLC Library

### ISSUE THREAD

**Issue by DC-Graphics** [shirriff/Arduino-IRremote#57] opened 2014-03-20 12:40 UTC
Looks like the timers / interrupts dont come along good.
Any ideas?

**Comment by z3t0** [comment] 2015-03-07 05:51
Can you please be more specific?

**Comment by z3t0** [comment] 2015-03-07 05:52
@DC-Graphics The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'

**Closed** 2015-03-08 07:11 UTC
Labels: Waiting for Feedback
