### ISSUE TITLE
Unexpected codeType 9

### ISSUE THREAD

**Issue by CrabbyPete** [shirriff/Arduino-IRremote#93] opened 2014-10-16 14:09 UTC
I am using an old Sony radio cassette remote control and testing with the example code. On these remotes the signal is pulsed out repeatedly. The IR gets it right the first time, but afterwords gets Unexpected codeType 9 and a value of FFFFFFFF

**Comment by z3t0** [comment] 2015-03-07 02:45
Have you tested this with the example provided? If not please provide the sketch used.

**Comment by z3t0** [comment] 2015-03-07 20:26
@CrabbyPete The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'.

**Closed by z3t0** 2015-03-07 20:26 UTC
Labels: Waiting for Feedback
