### ISSUE TITLE
Sony [Key0] receive - irrecv.decode(&results) never returns to 0 for no IR

### ISSUE THREAD

**Issue by robots42** [shirriff/Arduino-IRremote#50] opened 2014-02-03 09:11 UTC
Sony [Key0] receive - irrecv.decode(&results) never returns to 0 for no IR.
For all the other keys 
   irrecv.decode(&results)==1 if [a key] is pressed
   irrecv.decode(&results)==0 after [a key] is released
For [key 0] irrecv.decode(&results) locksup at 1 until a different key is pressed and released.
Tested with a genuine Sony Triniton IR remote and a PicAxe TVR010 IR remote, both give the same fault.

**Comment by z3t0** [comment] 2015-03-07 20:31
@robots42 The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'.

**Closed by z3t0** 2015-03-07 20:31 UTC
