### ISSUE TITLE
IRsendDemo won't compile

### ISSUE THREAD

**Issue by maddoggarage** [shirriff/Arduino-IRremote#25] opened 2013-04-02 04:13 UTC
Error messages are:
IRsend does not name a type
irsend was not declared in this scope

**Comment by joshl1995** [comment] 2015-02-16 13:22
I'm having the same problem, I have followed the installment instructions that were included with the library. Still nothing, I read somewhere before that the author posted that it was the Arduino, that doesn't even make sense because wasn't the library made to work on it?

**Comment by PaulStoffregen** [comment] 2015-02-16 18:42
First, delete the Robot libraries.  They interfere with IRremote.

If that doesn't solve your problems, you'll need to turn on verbose info while compiling in File > Preferences.  Then you can copy-and-paste detailed info about what actually happened and the actual error message into your request for help.

In Arduino 1.6.0 (just recently release), there's a "Copy Error Messages" button that appears when any error appears.  I know, because I contributed that code!  Please, use that button to conveniently copy the error to your clipboard.  Then you can paste it when writing a message asking for help.

**Comment by joshl1995** [comment] 2015-02-17 10:16
Thanks it worked!


------------------------------------------------------------
Randoma Programming, inc.
Email: contact@randoma.co
Website: http://randoma.co

**Comment by PaulStoffregen** [comment] 2015-03-06 16:59
A permanent fix for this problem is currently in limbo on Arduino's issue tracker.

https://github.com/arduino/Arduino/pull/2681

Please please please, if you encounter this problem, download and test the PR2681-BUILD191 copy of Arduino from that page.  If it works for you, please post some feedback on that pull request.  As more people test PR2681-BUILD191 and confirm it works, the odds of the Arduino devs merging this permanent fix will improve.

**Comment by z3t0** [comment] 2015-03-07 05:38
@PaulStoffregen Should this be marked as solved as the issue is not pertaining to this library, rather the Arduino Library *RobotIRRemote*

**Comment by ericwertz** [comment] 2015-03-07 08:34
This build fixed "the TKD2 problem" for me.  I had a code snippet, probably based on IRsendDemo, that broke immediately after loading 1.6.0 a couple weeks ago.

Date: Fri, 6 Mar 2015 08:59:22 -0800

**Comment by PaulStoffregen** [comment] 2015-03-07 11:33
If the fix worked for you, please tell the Arduino developers.  You need to post your comment on Arduino issue 2681 (or somewhere else they will see).  They'll never see your comment here, since this isn't their project.

@z3t0 Please leave this issue open until the Arduino developers merge the fix.  Yes, it's a problem in Arduino, not IRremote.... but we need to send more people over there to test the fix and add comments.  The only way this is ever going to actually get fixed in Arduino is if more people test the fix and ask them to accept it.

**Comment by z3t0** [comment] 2015-03-07 20:21
@PaulStoffregen OK no problem, but maybe we should clean it up and recreate this issue with a kind of guide at the top with possible solutions, including the ones listed above. Then we can leave the last option as reporting it on the Arduino 2681 Issue. My only concern is to make this issue more accessible by others so that Arduino is pushed to fix this problem, their library conflicts are getting a little frustrating.

**Comment by PaulStoffregen** [comment] 2015-03-09 22:46
Good news: Cristian Maglie, Arduino's lead developer, merged the fix today.  Arduino 1.6.1, and starting tomorrow Arduino's nightly builds, should solve this problem.

It's no longer necessary to leave this issue open for the purpose of encouraging people to give feedback to Arduino.  You might wish to keep this open as documentation, or try a nightly build or update to 1.6.1 after it's released.  Or perhaps create a new, better issue for that purpose?

Thanks for getting involved in IRremote's development & maintenance.  I had hoped to do more, but Teensy 3.x has kept me crazy busy for the last couple years!  If you'd like a free Teensy for testing IRremote or other stuff, please email me directly: paul at pjrc dot com.

**Comment by z3t0** [comment] 2015-03-09 22:48
Thanks for the awesome news! I'll close this issue as it has been solved but create a page in the wiki with the solutions on this page that have been suggested above.

**Closed by z3t0** 2015-03-09 22:48 UTC
Labels: Arduino Library Conflict

**Comment by sidharth-cb** [comment] 2017-04-22 11:17
Try this:
Just rename the folder of this library to 'IRremote'. It worked for me.

**Comment by contact-circularblue** [comment] 2017-04-22 11:18
Try this:
Just rename the folder of this library to 'IRremote'. It worked for me.

**Comment by z3t0** [comment] 2017-04-23 02:06
@contact-circularblue the releases folder always has them renamed as such!
